### ISSUE TITLE
StudyRecord. recordedTimeの型を制限する

### ISSUE THREAD

**Issue by koji-1009** [studyplus/Studyplus-Android-SDK-V2#16]
**機能が必要になった背景を記載してください**
今日より以前の日付の学習記録を登録したい場合、Stringに"yyyy'-'MM'-'dd' 'HH':'mm':'ss"形式で入力しなければならないが、SDKとして不親切な設計となっている

**どの様な機能が欲しいかを記載してください**
Date型で日付・時刻の指定が可能な状態にする。

**Comment by JASON13F** [comment]
**対応内容**
・学習日付(recordedTime)がString型とCalendar型の両方で設定できるようになっていたので、Calendar型のみ設定できるように変更
・Builderパターンの設計見直し
